name:                cuckoo-filter
version:             0.2.0.1
github:              "ChrisCoffey/cuckoo-filter"
license:             MIT
author:              "Chris Coffey"
maintainer:          "chris@foldl.io"
copyright:           "2018 Chris Coffey"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Pure and impure Cuckoo Filter
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ChrisCoffey/cuckoo-filter#readme>

dependencies:
- base >= 4.7 && < 5
- hashable
- containers
- cereal
- aeson
- array
- time
- bytestring

default-extensions: NamedFieldPuns DerivingStrategies ScopedTypeVariables DeriveGeneric MultiParamTypeClasses
    FunctionalDependencies FlexibleContexts FlexibleInstances

library:
    source-dirs: src
    exported-modules:
        Data.CuckooFilter,
        Data.CuckooFilter.Internal,
        Data.CuckooFilter.Mutable,
        Data.CuckooFilter.Pure
    ghc-options:
    - -O2

executables:
    benchmarks:
        main:               Benchmarks.hs
        source-dirs:        benchmarks
        other-modules:      Benchmarks.Simple,
                            Benchmarks.SpellChecker
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        - -O2
          #- -prof
          #- -fprof-auto
        dependencies:
        - cuckoo-filter
        - criterion
        - random

tests:
    cuckoo-filter-test:
        main:                Spec.hs
        source-dirs:         test
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - cuckoo-filter
        - tasty
        - tasty-quickcheck
        - tasty-hunit
        - QuickCheck
